In [5]:
!pwd
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

/content/drive/MyDrive/Github/sampledatafoodsales

In [2]:
!wget https://www.contextures.com/SampleData.zip

--2022-09-12 00:58:09--  https://www.contextures.com/SampleData.zip
Resolving www.contextures.com (www.contextures.com)... 34.94.142.247
Connecting to www.contextures.com (www.contextures.com)|34.94.142.247|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57647 (56K) [application/zip]
Saving to: ‘SampleData.zip’

SampleData.zip      100%[===================>]  56.30K  --.-KB/s    in 0.006s

2022-09-12 00:58:09 (9.00 MB/s) - ‘SampleData.zip’ saved [57647/57647]

In [3]:
!mkdir zip_content

In [5]:
!sudo apt-get install unzip

Reading package lists... Done
Building dependency tree
Reading state information... Done
unzip is already the newest version (6.0-21ubuntu1.1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.

In [6]:
!unzip SampleData.zip -d /content/zip_content/

Archive:  SampleData.zip
  inflating: /content/zip_content/SampleData.xlsx

In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

%cd zip_content/

df = pd.read_excel("SampleData.xlsx", sheet_name=None)

[Errno 2] No such file or directory: 'zip_content/'
/content/drive/MyDrive/Github/sampledatafoodsales

FileNotFoundError: ignored

In [13]:
df.keys()

dict_keys(['Instructions', 'SalesOrders', 'MyLinks'])

In [16]:
df['SalesOrders'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderDate  43 non-null     datetime64[ns]
 1   Region     43 non-null     object
 2   Rep        43 non-null     object
 3   Item       43 non-null     object
 4   Units      43 non-null     int64
 5   Unit Cost  43 non-null     float64
 6   Total      43 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 2.5+ KB

In [3]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/Github/
%cd sampledatafoodsales
%ls -l

Mounted at /content/drive
/content/drive/MyDrive/Github
/content/drive/MyDrive/Github/sampledatafoodsales
total 205
-rw------- 1 root root  83418 Sep 12 03:22 Financial.xlsx
-rw------- 1 root root 125836 Jul  3 20:10 sampledatafoodsales.xlsx

In [6]:

df = pd.read_excel("Financial.xlsx", sheet_name=None)

In [7]:
df['Sheet1'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        700 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [8]:
df_1 = df['Sheet1']

In [9]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        700 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [10]:
df_1

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [11]:
d_filter = df_1['Country'] == 'Canada'

In [18]:
d_f_product =  (df_1['Country'] == 'Canada') & (df_1['Product'] == 'Montana')

In [19]:
df_1[d_f_product]

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
7,Channel Partners,Canada,Montana,None,2518.0,5,12,30216.0,0.00,30216.00,7554.0,22662.00,2014-06-01,6,June,2014
11,Enterprise,Canada,Montana,None,2665.5,5,125,333187.5,0.00,333187.50,319860.0,13327.50,2014-07-01,7,July,2014
14,Enterprise,Canada,Montana,None,345.0,5,125,43125.0,0.00,43125.00,41400.0,1725.00,2013-10-01,10,October,2013
71,Government,Canada,Montana,Low,1830.0,5,7,12810.0,128.10,12681.90,9150.0,3531.90,2014-08-01,8,August,2014
183,Midmarket,Canada,Montana,Low,1967.0,5,15,29505.0,1180.20,28324.80,19670.0,8654.80,2014-03-01,3,March,2014
185,Government,Canada,Montana,Low,2851.0,5,7,19957.0,798.28,19158.72,14255.0,4903.72,2013-10-01,10,October,2013
357,Government,Canada,Montana,Medium,488.0,5,7,3416.0,273.28,3142.72,2440.0,702.72,2014-02-01,2,February,2014
365,Government,Canada,Montana,Medium,708.0,5,20,14160.0,1132.80,13027.20,7080.0,5947.20,2014-06-01,6,June,2014
368,Small Business,Canada,Montana,Medium,1283.0,5,300,384900.0,30792.00,354108.00,320750.0,33358.00,2013-09-01,9,September,2013
405,Small Business,Canada,Montana,Medium,3802.5,5,300,1140750.0,102667.50,1038082.50,950625.0,87457.50,2014-04-01,4,April,2014
408,Channel Partners,Canada,Montana,Medium,2321.0,5,12,27852.0,2506.68,25345.32,6963.0,18382.32,2014-11-01,11,November,2014
410,Government,Canada,Montana,Medium,1611.0,5,7,11277.0,1014.93,10262.07,8055.0,2207.07,2013-12-01,12,December,2013
543,Government,Canada,Montana,High,2734.0,5,7,19138.0,2296.56,16841.44,13670.0,3171.44,2014-10-01,10,October,2014
585,Government,Canada,Montana,High,1249.0,5,20,24980.0,3247.40,21732.60,12490.0,9242.60,2014-10-01,10,October,2014
632,Government,Canada,Montana,High,2227.5,5,350,779625.0,109147.50,670477.50,579150.0,91327.50,2014-01-01,1,January,2014
634,Government,Canada,Montana,High,200.0,5,350,70000.0,9800.00,60200.00,52000.0,8200.00,2014-05-01,5,May,2014
635,Government,Canada,Montana,High,388.0,5,7,2716.0,380.24,2335.76,1940.0,395.76,2014-09-01,9,September,2014
637,Midmarket,Canada,Montana,High,2300.0,5,15,34500.0,4830.00,29670.00,23000.0,6670.00,2014-12-01,12,December,2014

In [20]:
df_1[d_f_product]['Month Name'].value_counts()

October      4
June         2
September    2
December     2
July         1
August       1
March        1
February     1
April        1
November     1
January      1
May          1
Name: Month Name, dtype: int64

In [13]:
df_filter = df_1[d_filter]

In [15]:
df_filter['Product'].value_counts()

Paseo        42
VTT          22
Carretera    20
Velo         20
Montana      18
Amarilla     18
Name: Product, dtype: int64

In [21]:
cnt = df_1.groupby('Country')

In [22]:
cnt['Product'].value_counts()

Country                   Product
Canada                    Paseo        42
                          VTT          22
                          Carretera    20
                          Velo         20
                          Amarilla     18
                          Montana      18
France                    Paseo        40
                          VTT          22
                          Velo         22
                          Montana      20
                          Amarilla     18
                          Carretera    18
Germany                   Paseo        40
                          VTT          22
                          Velo         22
                          Carretera    20
                          Amarilla     18
                          Montana      18
Mexico                    Paseo        40
                          Velo         22
                          Amarilla     20
                          Montana      20
                          VTT          20
                          Carretera    18
United States of America  Paseo        40
                          VTT          23
                          Velo         23
                          Amarilla     20
                          Carretera    17
                          Montana      17
Name: Product, dtype: int64