In [1]:
!mkdir test_data
%cd test_data
!pwd

!wget https://github.com/chris1610/pbpython/blob/master/data/sales_transactions.xlsx?raw=true

/content/test_data
/content/test_data
--2022-09-17 07:55:35--  https://github.com/chris1610/pbpython/blob/master/data/sales_transactions.xlsx?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/chris1610/pbpython/raw/master/data/sales_transactions.xlsx [following]
--2022-09-17 07:55:35--  https://github.com/chris1610/pbpython/raw/master/data/sales_transactions.xlsx
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/chris1610/pbpython/master/data/sales_transactions.xlsx [following]
--2022-09-17 07:55:35--  https://raw.githubusercontent.com/chris1610/pbpython/master/data/sales_transactions.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5463 (5.3K) [application/octet-stream]
Saving to: ‘sales_transactions.xlsx?raw=true’

sales_transactions. 100%[===================>]   5.33K  --.-KB/s    in 0s

2022-09-17 07:55:35 (44.3 MB/s) - ‘sales_transactions.xlsx?raw=true’ saved [5463/5463]

In [2]:
!pwd
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

/content/test_data

In [3]:
df = pd.read_excel("sales_transactions.xlsx", sheet_name=None)

In [4]:
df.keys()

dict_keys(['Sheet1'])

In [5]:
df = pd.read_excel("sales_transactions.xlsx", sheet_name='Sheet1')

In [6]:
df

    account           name  order       sku  quantity  unit price  ext price
0    383080       Will LLC  10001  B1-20000         7       33.69     235.83
1    383080       Will LLC  10001  S1-27722        11       21.12     232.32
2    383080       Will LLC  10001  B1-86481         3       35.99     107.97
3    412290  Jerde-Hilpert  10005  S1-06532        48       55.82    2679.36
4    412290  Jerde-Hilpert  10005  S1-82801        21       13.62     286.02
5    412290  Jerde-Hilpert  10005  S1-06532         9       92.55     832.95
6    412290  Jerde-Hilpert  10005  S1-47412        44       78.91    3472.04
7    412290  Jerde-Hilpert  10005  S1-27722        36       25.42     915.12
8    218895      Kulas Inc  10006  S1-27722        32       95.66    3061.12
9    218895      Kulas Inc  10006  B1-33087        23       22.55     518.65
10   218895      Kulas Inc  10006  B1-33364         3       72.30     216.90
11   218895      Kulas Inc  10006  B1-20000        -1       72.18     -72.18

In [7]:

gr_sp = df.groupby('order')
df.groupby('order')['ext price'].sum()

order
10001     576.12
10005    8185.49
10006    3724.49
Name: ext price, dtype: float64

In [8]:
gr_sp.ngroups

3

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   account     12 non-null     int64
 1   name        12 non-null     object
 2   order       12 non-null     int64
 3   sku         12 non-null     object
 4   quantity    12 non-null     int64
 5   unit price  12 non-null     float64
 6   ext price   12 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 800.0+ bytes

In [10]:
gr_sp2 = df.groupby('order')['ext price'].sum()

In [11]:
gr_sp2.index

Int64Index([10001, 10005, 10006], dtype='int64', name='order')

In [12]:
gr_sp2.loc[10001]

576.12

In [13]:
df_sub_markup['bulk_buyer'] = df_sub_markup.apply(axis=1, func=Bulk_Buyer)

NameError: ignored

In [14]:

def Get_Order_percent(row_data):
  #get the order #
  order_num = row_data['order']
  #get total
  order_tot = gr_sp2.loc[order_num]
  #percent..
  part_per = row_data['ext price'] / order_tot
  return part_per

In [15]:
df_me = df.copy()
df_me['Percent_of_Order'] = df_me.apply(axis=1, func= Get_Order_percent)

In [16]:
df_me

,account,name,order,sku,quantity,unit price,ext price,Percent_of_Order
0,383080,Will LLC,10001,B1-20000,7,33.69,235.83,0.409342
1,383080,Will LLC,10001,S1-27722,11,21.12,232.32,0.403249
2,383080,Will LLC,10001,B1-86481,3,35.99,107.97,0.187409
3,412290,Jerde-Hilpert,10005,S1-06532,48,55.82,2679.36,0.327330
4,412290,Jerde-Hilpert,10005,S1-82801,21,13.62,286.02,0.034942
5,412290,Jerde-Hilpert,10005,S1-06532,9,92.55,832.95,0.101759
6,412290,Jerde-Hilpert,10005,S1-47412,44,78.91,3472.04,0.424170
7,412290,Jerde-Hilpert,10005,S1-27722,36,25.42,915.12,0.111798
8,218895,Kulas Inc,10006,S1-27722,32,95.66,3061.12,0.821890
9,218895,Kulas Inc,10006,B1-33087,23,22.55,518.65,0.139254
10,218895,Kulas Inc,10006,B1-33364,3,72.30,216.90,0.058236
11,218895,Kulas Inc,10006,B1-20000,-1,72.18,-72.18,-0.019380

In [17]:
df.groupby('order')['ext price'].transform('sum')

0      576.12
1      576.12
2      576.12
3     8185.49
4     8185.49
5     8185.49
6     8185.49
7     8185.49
8     3724.49
9     3724.49
10    3724.49
11    3724.49
Name: ext price, dtype: float64

In [18]:
df

    account           name  order       sku  quantity  unit price  ext price
0    383080       Will LLC  10001  B1-20000         7       33.69     235.83
1    383080       Will LLC  10001  S1-27722        11       21.12     232.32
2    383080       Will LLC  10001  B1-86481         3       35.99     107.97
3    412290  Jerde-Hilpert  10005  S1-06532        48       55.82    2679.36
4    412290  Jerde-Hilpert  10005  S1-82801        21       13.62     286.02
5    412290  Jerde-Hilpert  10005  S1-06532         9       92.55     832.95
6    412290  Jerde-Hilpert  10005  S1-47412        44       78.91    3472.04
7    412290  Jerde-Hilpert  10005  S1-27722        36       25.42     915.12
8    218895      Kulas Inc  10006  S1-27722        32       95.66    3061.12
9    218895      Kulas Inc  10006  B1-33087        23       22.55     518.65
10   218895      Kulas Inc  10006  B1-33364         3       72.30     216.90
11   218895      Kulas Inc  10006  B1-20000        -1       72.18     -72.18

In [ ]:
mean_purchase =df.groupby('User_ID')["Purchase"].mean().rename("User_mean").reset_index()

In [19]:
df_me

,account,name,order,sku,quantity,unit price,ext price,Percent_of_Order
0,383080,Will LLC,10001,B1-20000,7,33.69,235.83,0.409342
1,383080,Will LLC,10001,S1-27722,11,21.12,232.32,0.403249
2,383080,Will LLC,10001,B1-86481,3,35.99,107.97,0.187409
3,412290,Jerde-Hilpert,10005,S1-06532,48,55.82,2679.36,0.327330
4,412290,Jerde-Hilpert,10005,S1-82801,21,13.62,286.02,0.034942
5,412290,Jerde-Hilpert,10005,S1-06532,9,92.55,832.95,0.101759
6,412290,Jerde-Hilpert,10005,S1-47412,44,78.91,3472.04,0.424170
7,412290,Jerde-Hilpert,10005,S1-27722,36,25.42,915.12,0.111798
8,218895,Kulas Inc,10006,S1-27722,32,95.66,3061.12,0.821890
9,218895,Kulas Inc,10006,B1-33087,23,22.55,518.65,0.139254
10,218895,Kulas Inc,10006,B1-33364,3,72.30,216.90,0.058236
11,218895,Kulas Inc,10006,B1-20000,-1,72.18,-72.18,-0.019380

In [20]:
mean_quantity = df_me.groupby('order')['quantity'].mean().rename('quantity_mean').reset_index()

In [21]:
mean_quantity

   order  quantity_mean
0  10001           7.00
1  10005          31.60
2  10006          14.25

In [22]:
df_merge = df_me.merge(mean_quantity)

In [23]:
df_merge

,account,name,order,sku,quantity,unit price,ext price,Percent_of_Order,quantity_mean
0,383080,Will LLC,10001,B1-20000,7,33.69,235.83,0.409342,7.00
1,383080,Will LLC,10001,S1-27722,11,21.12,232.32,0.403249,7.00
2,383080,Will LLC,10001,B1-86481,3,35.99,107.97,0.187409,7.00
3,412290,Jerde-Hilpert,10005,S1-06532,48,55.82,2679.36,0.327330,31.60
4,412290,Jerde-Hilpert,10005,S1-82801,21,13.62,286.02,0.034942,31.60
5,412290,Jerde-Hilpert,10005,S1-06532,9,92.55,832.95,0.101759,31.60
6,412290,Jerde-Hilpert,10005,S1-47412,44,78.91,3472.04,0.424170,31.60
7,412290,Jerde-Hilpert,10005,S1-27722,36,25.42,915.12,0.111798,31.60
8,218895,Kulas Inc,10006,S1-27722,32,95.66,3061.12,0.821890,14.25
9,218895,Kulas Inc,10006,B1-33087,23,22.55,518.65,0.139254,14.25
10,218895,Kulas Inc,10006,B1-33364,3,72.30,216.90,0.058236,14.25
11,218895,Kulas Inc,10006,B1-20000,-1,72.18,-72.18,-0.019380,14.25