In [2]:
import pandas as pd
import numpy as np

In [1]:
!wget https://github.com/selva86/datasets/raw/master/supermarket_sales.csv

--2022-10-13 08:45:19--  https://github.com/selva86/datasets/raw/master/supermarket_sales.csv
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/selva86/datasets/master/supermarket_sales.csv [following]
--2022-10-13 08:45:20--  https://raw.githubusercontent.com/selva86/datasets/master/supermarket_sales.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 131528 (128K) [text/plain]
Saving to: ‘supermarket_sales.csv’

supermarket_sales.c 100%[===================>] 128.45K  --.-KB/s    in 0.01s

2022-10-13 08:45:20 (8.65 MB/s) - ‘supermarket_sales.csv’ saved [131528/131528]

In [4]:
df = pd.read_csv('supermarket_sales.csv')
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [5]:
df_sort = df.sort_values('Branch')
df_sort

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
530,287-83-1405,A,Yangon,Normal,Male,Health and beauty,25.43,6,7.6290,160.2090,2/12/2019,19:01,Ewallet,152.58,4.761905,7.6290,7.0
529,827-77-7633,A,Yangon,Normal,Male,Sports and travel,98.09,9,44.1405,926.9505,2/17/2019,19:41,Cash,882.81,4.761905,44.1405,9.3
525,719-89-8991,A,Yangon,Member,Female,Sports and travel,91.41,5,22.8525,479.9025,2/25/2019,16:03,Ewallet,457.05,4.761905,22.8525,7.1
524,534-01-4457,A,Yangon,Normal,Male,Food and beverages,81.71,6,24.5130,514.7730,1/27/2019,14:36,Credit card,490.26,4.761905,24.5130,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,779-06-0012,C,Naypyitaw,Member,Female,Home and lifestyle,88.61,1,4.4305,93.0405,1/19/2019,10:21,Cash,88.61,4.761905,4.4305,7.7
613,284-54-4231,C,Naypyitaw,Member,Male,Sports and travel,80.93,1,4.0465,84.9765,1/19/2019,16:08,Credit card,80.93,4.761905,4.0465,9.0
611,277-35-5865,C,Naypyitaw,Member,Female,Food and beverages,98.97,9,44.5365,935.2665,3/9/2019,11:23,Cash,890.73,4.761905,44.5365,6.7
641,155-45-3814,C,Naypyitaw,Member,Female,Electronic accessories,88.55,8,35.4200,743.8200,3/19/2019,15:29,Ewallet,708.40,4.761905,35.4200,4.7
663,641-51-2661,C,Naypyitaw,Member,Female,Food and beverages,87.10,10,43.5500,914.5500,2/12/2019,14:45,Credit card,871.00,4.761905,43.5500,9.9

In [6]:
df_sort = df.sort_values(['Branch', 'Payment'])
df_sort

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
14,829-34-3910,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,19:21,Cash,713.80,4.761905,35.6900,5.7
29,848-62-7243,A,Yangon,Normal,Male,Health and beauty,24.89,9,11.2005,235.2105,3/15/2019,15:36,Cash,224.01,4.761905,11.2005,7.4
51,162-48-8011,A,Yangon,Member,Female,Food and beverages,44.59,5,11.1475,234.0975,2/10/2019,15:10,Cash,222.95,4.761905,11.1475,8.5
56,106-35-6779,A,Yangon,Member,Male,Home and lifestyle,44.34,2,4.4340,93.1140,3/27/2019,11:26,Cash,88.68,4.761905,4.4340,5.8
58,817-48-8732,A,Yangon,Member,Female,Home and lifestyle,72.35,10,36.1750,759.6750,1/20/2019,15:55,Cash,723.50,4.761905,36.1750,5.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,500-02-2261,C,Naypyitaw,Normal,Female,Food and beverages,57.29,6,17.1870,360.9270,3/21/2019,17:04,Ewallet,343.74,4.761905,17.1870,5.9
948,373-88-1424,C,Naypyitaw,Member,Male,Home and lifestyle,35.81,5,8.9525,188.0025,2/6/2019,18:44,Ewallet,179.05,4.761905,8.9525,7.9
988,267-62-7380,C,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,19:12,Ewallet,823.40,4.761905,41.1700,4.3
994,652-49-6720,C,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40,Ewallet,60.95,4.761905,3.0475,5.9
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2