In [1]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/Github/
%cd sampledatafoodsales
%ls -a

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

df = pd.read_excel("sampledatafoodsales.xlsx", sheet_name="FoodSales")

Mounted at /content/drive
/content/drive/MyDrive/Github
/content/drive/MyDrive/Github/sampledatafoodsales
sampledatafoodsales.xlsx

In [2]:
df

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
0,2020-01-01,East,Boston,Bars,Carrot,33.0,1.77,58.41
1,2020-01-04,East,Boston,Crackers,Whole Wheat,87.0,3.49,303.63
2,2020-01-07,West,Los Angeles,Cookies,Chocolate Chip,58.0,1.87,108.46
3,2020-01-10,East,New York,Cookies,Chocolate Chip,82.0,1.87,153.34
4,2020-01-13,East,Boston,Cookies,Arrowroot,38.0,2.18,82.84
...,...,...,...,...,...,...,...,...
239,2021-12-18,East,Boston,Cookies,Arrowroot,34.0,2.18,74.12
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245.0,1.87,458.15
241,2021-12-24,East,Boston,Crackers,Whole Wheat,30.0,3.49,104.70
242,2021-12-27,West,Los Angeles,Bars,Bran,30.0,1.87,56.10
243,2021-12-30,West,Los Angeles,Cookies,Oatmeal Raisin,44.0,2.84,124.96

In [4]:
df.sort_values(by='Product')

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
121,2020-12-30,West,San Diego,Cookies,Arrowroot,83.0,2.18,180.94
191,2021-07-27,West,Los Angeles,Cookies,Arrowroot,20.0,2.18,43.60
185,2021-07-09,East,New York,Cookies,Arrowroot,37.0,2.18,80.66
171,2021-05-28,West,San Diego,Cookies,Arrowroot,36.0,2.18,78.48
48,2020-05-25,East,Boston,Cookies,Arrowroot,27.0,2.18,58.86
...,...,...,...,...,...,...,...,...
50,2020-05-31,East,Boston,Crackers,Whole Wheat,33.0,3.49,115.17
56,2020-06-18,East,Boston,Crackers,Whole Wheat,38.0,3.49,132.62
54,2020-06-12,West,San Diego,Crackers,Whole Wheat,20.0,3.49,69.80
78,2020-08-23,East,Boston,Crackers,Whole Wheat,21.0,3.49,73.29
97,2020-10-19,East,New York,Crackers,Whole Wheat,32.0,3.49,111.68

In [6]:
df.sort_values(by=['Product', 'City'], inplace=True)

In [7]:
df

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
4,2020-01-13,East,Boston,Cookies,Arrowroot,38.0,2.18,82.84
10,2020-01-31,East,Boston,Cookies,Arrowroot,36.0,2.18,78.48
16,2020-02-18,East,Boston,Cookies,Arrowroot,43.0,2.18,93.74
48,2020-05-25,East,Boston,Cookies,Arrowroot,27.0,2.18,58.86
76,2020-08-17,East,Boston,Cookies,Arrowroot,31.0,2.18,67.58
...,...,...,...,...,...,...,...,...
97,2020-10-19,East,New York,Crackers,Whole Wheat,32.0,3.49,111.68
128,2021-01-20,East,New York,Crackers,Whole Wheat,31.0,3.49,108.19
237,2021-12-12,East,New York,Crackers,Whole Wheat,25.0,3.49,87.25
54,2020-06-12,West,San Diego,Crackers,Whole Wheat,20.0,3.49,69.80
62,2020-07-06,West,San Diego,Crackers,Whole Wheat,28.0,3.49,97.72

In [10]:
df.sort_index(inplace=True)

In [11]:
df

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
0,2020-01-01,East,Boston,Bars,Carrot,33.0,1.77,58.41
1,2020-01-04,East,Boston,Crackers,Whole Wheat,87.0,3.49,303.63
2,2020-01-07,West,Los Angeles,Cookies,Chocolate Chip,58.0,1.87,108.46
3,2020-01-10,East,New York,Cookies,Chocolate Chip,82.0,1.87,153.34
4,2020-01-13,East,Boston,Cookies,Arrowroot,38.0,2.18,82.84
...,...,...,...,...,...,...,...,...
239,2021-12-18,East,Boston,Cookies,Arrowroot,34.0,2.18,74.12
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245.0,1.87,458.15
241,2021-12-24,East,Boston,Crackers,Whole Wheat,30.0,3.49,104.70
242,2021-12-27,West,Los Angeles,Bars,Bran,30.0,1.87,56.10
243,2021-12-30,West,Los Angeles,Cookies,Oatmeal Raisin,44.0,2.84,124.96

In [13]:
df.sort_values(by=['City','UnitPrice'], ascending=[True,False])

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
50,2020-05-31,East,Boston,Crackers,Whole Wheat,33.0,3.49,115.17
56,2020-06-18,East,Boston,Crackers,Whole Wheat,38.0,3.49,132.62
64,2020-07-12,East,Boston,Crackers,Whole Wheat,42.0,3.49,146.58
78,2020-08-23,East,Boston,Crackers,Whole Wheat,21.0,3.49,73.29
92,2020-10-04,East,Boston,Crackers,Whole Wheat,38.0,3.49,132.62
...,...,...,...,...,...,...,...,...
179,2021-06-21,West,San Diego,Bars,Carrot,41.0,1.77,72.57
201,2021-08-26,West,San Diego,Bars,Carrot,41.0,1.77,72.57
34,2020-04-13,West,San Diego,Snacks,Potato Chips,28.0,1.68,47.04
69,2020-07-27,West,San Diego,Snacks,Potato Chips,31.0,1.68,52.08
145,2021-03-11,West,San Diego,Snacks,Potato Chips,41.0,1.68,68.88

In [14]:
df['Quantity'].nlargest(10)

57     306.0
51     288.0
240    245.0
119    237.0
141    232.0
95     224.0
232    211.0
29     193.0
215    175.0
6      149.0
Name: Quantity, dtype: float64

In [15]:
df.nlargest(10,columns='Quantity')

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
57,2020-06-21,West,Los Angeles,Bars,Carrot,306.0,1.77,541.62
51,2020-06-03,West,Los Angeles,Cookies,Oatmeal Raisin,288.0,2.84,817.92
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245.0,1.87,458.15
119,2020-12-24,East,New York,Cookies,Arrowroot,237.0,2.18,516.66
141,2021-02-28,West,Los Angeles,Cookies,Chocolate Chip,232.0,1.87,433.84
95,2020-10-13,East,New York,Cookies,Arrowroot,224.0,2.18,488.32
232,2021-11-27,East,Boston,Cookies,Chocolate Chip,211.0,1.87,394.57
29,2020-03-29,East,Boston,Cookies,Oatmeal Raisin,193.0,2.84,548.12
215,2021-10-07,East,New York,Cookies,Arrowroot,175.0,2.18,381.50
6,2020-01-19,East,Boston,Crackers,Whole Wheat,149.0,3.49,520.01