In [1]:
!pwd
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

/content

In [2]:
!wget https://theunitedstates.io/congress-legislators/legislators-historical.csv

--2022-09-13 01:13:30--  https://theunitedstates.io/congress-legislators/legislators-historical.csv
Resolving theunitedstates.io (theunitedstates.io)... 185.199.108.153, 185.199.109.153, 185.199.111.153, ...
Connecting to theunitedstates.io (theunitedstates.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1460659 (1.4M) [text/csv]
Saving to: ‘legislators-historical.csv’

legislators-histori 100%[===================>]   1.39M  --.-KB/s    in 0.07s

2022-09-13 01:13:30 (20.1 MB/s) - ‘legislators-historical.csv’ saved [1460659/1460659]

In [19]:
dtypes = {
    "first_name": "category",
    "gender": "category",
    "type": "category",
    "state": "category",
    "party": "category",
}
df = pd.read_csv(
    "legislators-historical.csv",
    dtype=dtypes,
    usecols=list(dtypes) + ["birthday", "last_name"],
    parse_dates=["birthday"]
)

In [5]:
df.tail()

      last_name first_name   birthday gender type state       party
12053      Vela    Filemon 1963-02-13      M  rep    TX    Democrat
12054      Reed        Tom 1971-11-18      M  rep    NY  Republican
12055   Delgado    Antonio 1977-01-19      M  rep    NY    Democrat
12056  Walorski     Jackie 1963-08-17      F  rep    IN  Republican
12057     Crist    Charlie 1956-07-24      M  rep    FL    Democrat

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12058 entries, 0 to 12057
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   last_name   12058 non-null  object
 1   first_name  12058 non-null  category
 2   birthday    11508 non-null  datetime64[ns]
 3   gender      12058 non-null  category
 4   type        12058 non-null  category
 5   state       12058 non-null  category
 6   party       11826 non-null  category
dtypes: category(5), datetime64[ns](1), object(1)
memory usage: 309.0+ KB

In [21]:
df

      last_name  first_name   birthday gender type state                party
0       Bassett     Richard 1745-04-02      M  sen    DE  Anti-Administration
1         Bland  Theodorick 1742-03-21      M  rep    VA                  NaN
2         Burke     Aedanus 1743-06-16      M  rep    SC                  NaN
3       Carroll      Daniel 1730-07-22      M  rep    MD                  NaN
4        Clymer      George 1739-03-16      M  rep    PA                  NaN
...         ...         ...        ...    ...  ...   ...                  ...
12053      Vela     Filemon 1963-02-13      M  rep    TX             Democrat
12054      Reed         Tom 1971-11-18      M  rep    NY           Republican
12055   Delgado     Antonio 1977-01-19      M  rep    NY             Democrat
12056  Walorski      Jackie 1963-08-17      F  rep    IN           Republican
12057     Crist     Charlie 1956-07-24      M  rep    FL             Democrat

[12058 rows x 7 columns]

In [9]:
df.dtypes

last_name             object
first_name          category
birthday      datetime64[ns]
gender              category
type                category
state               category
party               category
dtype: object

In [22]:
n_by_state = df.groupby("state")["last_name"].count()

In [28]:
p_by_state = df.groupby(['state','party'])['last_name'].count()

In [29]:
p_by_state

state  party
AK     Adams             0
       Adams Democrat    0
       American          0
       American Labor    0
       Anti Jackson      0
                        ..
WY     Union Democrat    0
       Union Labor       0
       Unionist          0
       Unknown           0
       Whig              0
Name: last_name, Length: 3480, dtype: int64

In [33]:
p_by_state['AK']

party
Adams                         0
Adams Democrat                0
American                      0
American Labor                0
Anti Jackson                  0
Anti Jacksonian               0
Anti Masonic                  0
Anti-Administration           0
Anti-Jacksonian               0
Anti-Lecompton Democrat       0
Coalitionist                  0
Conservative                  0
Conservative Republican       0
Constitutional Unionist       0
Crawford Republican           0
Democrat                      8
Democrat-Liberal              0
Democratic Republican         0
Democratic and Union Labor    0
Farmer-Labor                  0
Federalist                    0
Free Silver                   0
Free Soil                     0
Ind. Democrat                 0
Ind. Republican               0
Ind. Republican-Democrat      0
Ind. Whig                     0
Independent                   1
Independent Democrat          0
Jackson                       0
Jackson Republican            0
Jacksonian                    0
Law and Order                 0
Liberal Republican            0
Libertarian                   0
Liberty                       0
National Greenbacker          0
New Progressive               0
Nonpartisan                   0
Nullifier                     0
Popular Democrat              0
Populist                      0
Pro-Administration            0
Progressive                   0
Progressive Republican        0
Prohibitionist                0
Readjuster                    0
Readjuster Democrat           0
Republican                    6
Republican-Conservative       0
Silver Republican             0
Socialist                     0
States Rights                 0
Unconditional Unionist        0
Union                         0
Union Democrat                0
Union Labor                   0
Unionist                      0
Unknown                       0
Whig                          0
Name: last_name, dtype: int64

In [23]:
n_by_state

state
AK      17
AL     209
AR     117
AS       2
AZ      49
CA     368
CO      92
CT     240
DC       2
DE      97
DK       9
FL     162
GA     317
GU       4
HI      24
IA     205
ID      59
IL     488
IN     344
KS     143
KY     373
LA     199
MA     427
MD     305
ME     175
MI     296
MN     162
MO     334
MS     155
MT      53
NC     356
ND      44
NE     128
NH     181
NJ     359
NM      57
NV      56
NY    1469
OH     676
OK      93
OL       2
OR      90
PA    1053
PI      13
PR      19
RI     107
SC     251
SD      51
TN     301
TX     264
UT      55
VA     433
VI       4
VT     115
WA      96
WI     198
WV     120
WY      40
Name: last_name, dtype: int64

In [24]:
ak_filter = df['state'] == 'AK'

In [25]:
df[ak_filter]

        last_name first_name   birthday gender type state        party
6617       Waskey      Frank 1875-04-20      M  rep    AK     Democrat
6645         Cale     Thomas 1848-09-17      M  rep    AK  Independent
7440      Grigsby     George 1874-12-02      M  rep    AK          NaN
7499       Sulzer    Charles 1879-02-24      M  rep    AK          NaN
8037   Sutherland     Daniel 1869-04-17      M  rep    AK   Republican
8234   Wickersham      James 1857-08-24      M  rep    AK   Republican
8875       Dimond    Anthony 1881-11-30      M  rep    AK     Democrat
9817     Gruening     Ernest 1887-02-06      M  sen    AK     Democrat
9949       Rivers      Ralph 1903-05-23      M  rep    AK     Democrat
9983     Bartlett     Edward 1904-04-20      M  sen    AK     Democrat
10080     Pollock     Howard 1920-04-11      M  rep    AK   Republican
10106      Begich   Nicholas 1932-04-06      M  rep    AK     Democrat
10323      Gravel    Maurice 1930-05-13      M  sen    AK     Democrat
11259   Murkowski      Frank 1933-03-28      M  sen    AK   Republican
11383     Stevens        Ted 1923-11-18      M  sen    AK   Republican
11731      Begich       Mark 1962-03-30      M  sen    AK     Democrat
12051       Young        Don 1933-06-09      M  rep    AK   Republican

TypeError: ignored