In [ ]:

import pandas as pd
import numpy as np

data_1 = {'product_1': ['computer','monitor','printer','desk'],
                   'price_1': [1200,800,200,350]
                   }
df1 = pd.DataFrame(data_1)


data_2 = {'product_2': ['computer','monitor','printer','desk'],
                    'price_2': [900,800,300,350]
                    }
df2 = pd.DataFrame(data_2)


df1['price_2'] = df2['price_2'] #add the price_2 column from df2 to df1
df1['prices_match'] = np.where(df1['price_1'] == df2['price_2'], 'True', 'False') #create a new column in df1 to check if prices match
df1['price_diff'] = np.where(df1['price_1'] == df2['price_2'], 0, df1['price_1'] - df2['price_2']) #create a new column in df1 for price diff

print(df1)

  product_1  price_1  price_2 prices_match  price_diff
0  computer     1200      900        False         300
1   monitor      800      800         True           0
2   printer      200      300        False        -100
3      desk      350      350         True           0

In [ ]:

print(df1.equals(df2))

False

In [ ]:

# creating and initializing a nested list
age_list = [['Afghanistan', 1952, 8425333, 'Asia'],
            ['Australia', 1957, 9712569, 'Oceania'],
            ['Brazil', 1962, 76039390, 'Americas'],
            ['China', 1957, 637408000, 'Asia'],
            ['France', 1957, 44310863, 'Europe'],
            ['India', 1952, 3.72e+08, 'Asia'],
            ['United States', 1957, 171984000, 'Americas']]
  
# creating a pandas dataframe
df = pd.DataFrame(age_list, columns=['Country', 'Year',
                                     'Population', 'Continent'])

print(df)

         Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [ ]:

# Sorting by column "Population"
df.sort_values(by=['Population'], ascending=False)

         Country  Year   Population Continent
3          China  1957  637408000.0      Asia
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas
2         Brazil  1962   76039390.0  Americas
4         France  1957   44310863.0    Europe
1      Australia  1957    9712569.0   Oceania
0    Afghanistan  1952    8425333.0      Asia

In [ ]:

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/JackyP/testing/master/datasets/nycflights.csv", usecols=range(1,17))

In [ ]:
print(df.head())

   year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
0  2013      1    1     517.0        2.0     830.0       11.0      UA  N14228
1  2013      1    1     533.0        4.0     850.0       20.0      UA  N24211
2  2013      1    1     542.0        2.0     923.0       33.0      AA  N619AA
3  2013      1    1     544.0       -1.0    1004.0      -18.0      B6  N804JB
4  2013      1    1     554.0       -6.0     812.0      -25.0      DL  N668DN

   flight origin dest  air_time  distance  hour  minute
0    1545    EWR  IAH     227.0      1400   5.0    17.0
1    1714    LGA  IAH     227.0      1416   5.0    33.0
2    1141    JFK  MIA     160.0      1089   5.0    42.0
3     725    JFK  BQN     183.0      1576   5.0    44.0
4     461    LGA  ATL     116.0       762   5.0    54.0

In [ ]:

newdf = df[(df.origin == "JFK") & (df.carrier == "B6")]
print(newdf.head())

    year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
3   2013      1    1     544.0       -1.0    1004.0      -18.0      B6
8   2013      1    1     557.0       -3.0     838.0       -8.0      B6
10  2013      1    1     558.0       -2.0     849.0       -2.0      B6
11  2013      1    1     558.0       -2.0     853.0       -3.0      B6
15  2013      1    1     559.0        0.0     702.0       -4.0      B6

   tailnum  flight origin dest  air_time  distance  hour  minute
3   N804JB     725    JFK  BQN     183.0      1576   5.0    44.0
8   N593JB      79    JFK  MCO     140.0       944   5.0    57.0
10  N793JB      49    JFK  PBI     149.0      1028   5.0    58.0
11  N657JB      71    JFK  TPA     158.0      1005   5.0    58.0
15  N708JB    1806    JFK  BOS      44.0       187   5.0    59.0

In [ ]:

newdf = df.query('origin == "JFK" & carrier == "B6"')
print(newdf.head())

    year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
3   2013      1    1     544.0       -1.0    1004.0      -18.0      B6
8   2013      1    1     557.0       -3.0     838.0       -8.0      B6
10  2013      1    1     558.0       -2.0     849.0       -2.0      B6
11  2013      1    1     558.0       -2.0     853.0       -3.0      B6
15  2013      1    1     559.0        0.0     702.0       -4.0      B6

   tailnum  flight origin dest  air_time  distance  hour  minute
3   N804JB     725    JFK  BQN     183.0      1576   5.0    44.0
8   N593JB      79    JFK  MCO     140.0       944   5.0    57.0
10  N793JB      49    JFK  PBI     149.0      1028   5.0    58.0
11  N657JB      71    JFK  TPA     158.0      1005   5.0    58.0
15  N708JB    1806    JFK  BOS      44.0       187   5.0    59.0

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/Github/
%cd sampledatafoodsales
%ls -a

/content/drive/MyDrive/Github
/content/drive/MyDrive/Github/sampledatafoodsales
sampledatafoodsales.xlsx

In [3]:

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

df = pd.read_excel("sampledatafoodsales.xlsx", sheet_name="FoodSales")

In [4]:
df

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
0,2020-01-01,East,Boston,Bars,Carrot,33.0,1.77,58.41
1,2020-01-04,East,Boston,Crackers,Whole Wheat,87.0,3.49,303.63
2,2020-01-07,West,Los Angeles,Cookies,Chocolate Chip,58.0,1.87,108.46
3,2020-01-10,East,New York,Cookies,Chocolate Chip,82.0,1.87,153.34
4,2020-01-13,East,Boston,Cookies,Arrowroot,38.0,2.18,82.84
...,...,...,...,...,...,...,...,...
239,2021-12-18,East,Boston,Cookies,Arrowroot,34.0,2.18,74.12
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245.0,1.87,458.15
241,2021-12-24,East,Boston,Crackers,Whole Wheat,30.0,3.49,104.70
242,2021-12-27,West,Los Angeles,Bars,Bran,30.0,1.87,56.10
243,2021-12-30,West,Los Angeles,Cookies,Oatmeal Raisin,44.0,2.84,124.96

In [6]:
sp_filter = df['City'] == "Boston"

In [7]:
df[sp_filter]

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
0,2020-01-01,East,Boston,Bars,Carrot,33.0,1.77,58.41
1,2020-01-04,East,Boston,Crackers,Whole Wheat,87.0,3.49,303.63
4,2020-01-13,East,Boston,Cookies,Arrowroot,38.0,2.18,82.84
5,2020-01-16,East,Boston,Bars,Carrot,54.0,1.77,95.58
6,2020-01-19,East,Boston,Crackers,Whole Wheat,149.0,3.49,520.01
...,...,...,...,...,...,...,...,...
232,2021-11-27,East,Boston,Cookies,Chocolate Chip,211.0,1.87,394.57
233,2021-11-30,East,Boston,Crackers,Whole Wheat,20.0,3.49,69.80
239,2021-12-18,East,Boston,Cookies,Arrowroot,34.0,2.18,74.12
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245.0,1.87,458.15
241,2021-12-24,East,Boston,Crackers,Whole Wheat,30.0,3.49,104.70

In [8]:
 df.loc[sp_filter,['Category','Product']]

     Category         Product
0        Bars          Carrot
1    Crackers     Whole Wheat
4     Cookies       Arrowroot
5        Bars          Carrot
6    Crackers     Whole Wheat
..        ...             ...
232   Cookies  Chocolate Chip
233  Crackers     Whole Wheat
239   Cookies       Arrowroot
240   Cookies  Chocolate Chip
241  Crackers     Whole Wheat

[88 rows x 2 columns]

In [13]:
sp2_filter = (df['Category'] == 'Cookies') & (df['Quantity'] > 50) 

df_sp2 = df.loc[sp2_filter]

In [17]:
sp_cookies_pivot = df_sp2.pivot_table(index='City', columns='Product', values='TotalPrice', fill_value=0, aggfunc=['sum'])
sp_cookies_pivot

                  sum
Product     Arrowroot Chocolate Chip Oatmeal Raisin
City
Boston        1079.10         852.72        3362.56
Los Angeles    294.30        1421.20        1723.88
New York      1944.56         697.51         974.12
San Diego      904.70         809.71           0.00

In [19]:
sp_wheat = (df['Product'].str.contains('Chip'))

df[sp_wheat]

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
2,2020-01-07,West,Los Angeles,Cookies,Chocolate Chip,58.0,1.87,108.46
3,2020-01-10,East,New York,Cookies,Chocolate Chip,82.0,1.87,153.34
9,2020-01-28,East,New York,Snacks,Potato Chips,28.0,1.35,37.80
11,2020-02-03,East,Boston,Cookies,Chocolate Chip,31.0,1.87,57.97
15,2020-02-15,East,New York,Snacks,Potato Chips,27.0,1.35,36.45
20,2020-03-02,East,New York,Cookies,Chocolate Chip,85.0,1.87,158.95
24,2020-03-14,West,Los Angeles,Cookies,Chocolate Chip,86.0,1.87,160.82
26,2020-03-20,East,New York,Snacks,Potato Chips,68.0,1.68,114.24
27,2020-03-23,West,San Diego,Cookies,Chocolate Chip,39.0,1.87,72.93
31,2020-04-04,West,Los Angeles,Snacks,Potato Chips,68.0,1.68,114.24
34,2020-04-13,West,San Diego,Snacks,Potato Chips,28.0,1.68,47.04
36,2020-04-19,East,Boston,Snacks,Potato Chips,134.0,1.68,225.12
39,2020-04-28,East,New York,Snacks,Potato Chips,64.0,1.68,107.52
40,2020-05-01,West,San Diego,Cookies,Chocolate Chip,63.0,1.87,117.81
46,2020-05-19,East,New York,Snacks,Potato Chips,49.0,1.68,82.32
47,2020-05-22,West,San Diego,Cookies,Chocolate Chip,55.0,1.87,102.85
52,2020-06-06,East,New York,Cookies,Chocolate Chip,76.0,1.87,142.12
58,2020-06-24,West,Los Angeles,Snacks,Potato Chips,28.0,1.68,47.04
65,2020-07-15,West,Los Angeles,Cookies,Chocolate Chip,75.0,1.87,140.25
69,2020-07-27,West,San Diego,Snacks,Potato Chips,31.0,1.68,52.08
72,2020-08-05,West,Los Angeles,Cookies,Chocolate Chip,107.0,1.87,200.09
75,2020-08-14,West,San Diego,Cookies,Chocolate Chip,70.0,1.87,130.90
79,2020-08-26,West,Los Angeles,Cookies,Chocolate Chip,80.0,1.87,149.60
88,2020-09-22,East,New York,Cookies,Chocolate Chip,65.0,1.87,121.55
94,2020-10-10,West,Los Angeles,Snacks,Potato Chips,114.0,1.68,191.52
100,2020-10-28,East,Boston,Cookies,Chocolate Chip,49.0,1.87,91.63
103,2020-11-06,West,Los Angeles,Snacks,Potato Chips,62.0,1.68,104.16
110,2020-11-27,West,Los Angeles,Snacks,Potato Chips,29.0,1.68,48.72
115,2020-12-12,East,Boston,Cookies,Chocolate Chip,36.0,1.87,67.32
118,2020-12-21,West,Los Angeles,Snacks,Potato Chips,29.0,1.68,48.72
120,2020-12-27,East,New York,Cookies,Chocolate Chip,65.0,1.87,121.55
132,2021-02-01,East,Boston,Snacks,Potato Chips,24.0,1.68,40.32
134,2021-02-07,West,Los Angeles,Cookies,Chocolate Chip,34.0,1.87,63.58
136,2021-02-13,East,New York,Snacks,Potato Chips,21.0,1.68,35.28
141,2021-02-28,West,Los Angeles,Cookies,Chocolate Chip,232.0,1.87,433.84
145,2021-03-11,West,San Diego,Snacks,Potato Chips,41.0,1.68,68.88
147,2021-03-17,East,Boston,Snacks,Potato Chips,47.0,1.68,78.96
149,2021-03-23,West,Los Angeles,Snacks,Potato Chips,33.0,1.68,55.44
158,2021-04-19,East,New York,Snacks,Potato Chips,24.0,1.68,40.32
159,2021-04-22,West,San Diego,Cookies,Chocolate Chip,67.0,1.87,125.29
163,2021-05-04,West,Los Angeles,Cookies,Chocolate Chip,58.0,1.87,108.46
166,2021-05-13,West,San Diego,Cookies,Chocolate Chip,82.0,1.87,153.34
169,2021-05-22,West,Los Angeles,Cookies,Chocolate Chip,43.0,1.87,80.41
181,2021-06-27,East,Boston,Cookies,Chocolate Chip,38.0,1.87,71.06
186,2021-07-12,East,New York,Cookies,Chocolate Chip,40.0,1.87,74.80
189,2021-07-21,East,Boston,Cookies,Chocolate Chip,32.0,1.87,59.84
192,2021-07-30,West,Los Angeles,Cookies,Chocolate Chip,64.0,1.87,119.68
208,2021-09-16,East,New York,Snacks,Potato Chips,20.0,1.68,33.60
216,2021-10-10,East,New York,Cookies,Chocolate Chip,23.0,1.87,43.01
223,2021-10-31,East,New York,Snacks,Potato Chips,25.0,1.68,42.00
224,2021-11-03,West,San Diego,Cookies,Chocolate Chip,24.0,1.87,44.88
229,2021-11-18,East,New York,Cookies,Chocolate Chip,34.0,1.87,63.58
232,2021-11-27,East,Boston,Cookies,Chocolate Chip,211.0,1.87,394.57
238,2021-12-15,West,San Diego,Cookies,Chocolate Chip,96.0,1.87,179.52
240,2021-12-21,East,Boston,Cookies,Chocolate Chip,245.0,1.87,458.15