In [1]:
!mkdir new_data
%cd new_data
!pwd

/content/new_data
/content/new_data

In [2]:
!wget https://store.pangaea.de/Publications/IizumiT_2019/gdhy_v1.2_v1.3_20190128.zip

--2022-09-26 06:56:04--  https://store.pangaea.de/Publications/IizumiT_2019/gdhy_v1.2_v1.3_20190128.zip
Resolving store.pangaea.de (store.pangaea.de)... 134.1.2.171
Connecting to store.pangaea.de (store.pangaea.de)|134.1.2.171|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15989683 (15M) [application/zip]
Saving to: ‘gdhy_v1.2_v1.3_20190128.zip’

gdhy_v1.2_v1.3_2019 100%[===================>]  15.25M  11.2MB/s    in 1.4s

2022-09-26 06:56:06 (11.2 MB/s) - ‘gdhy_v1.2_v1.3_20190128.zip’ saved [15989683/15989683]

In [6]:
!apt install unzip

Reading package lists... Done
Building dependency tree
Reading state information... Done
unzip is already the newest version (6.0-21ubuntu1.1).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.

In [ ]:
!unzip gdhy.zip

In [8]:
!wget https://apps.bea.gov/industry/xls/io-annual/Use_SUT_Framework_2007_2012_DET.xlsx

--2022-09-26 07:09:23--  https://apps.bea.gov/industry/xls/io-annual/Use_SUT_Framework_2007_2012_DET.xlsx
Resolving apps.bea.gov (apps.bea.gov)... 192.149.12.17, 2610:20:3006:1::25
Connecting to apps.bea.gov (apps.bea.gov)|192.149.12.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1467803 (1.4M) [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet]
Saving to: ‘Use_SUT_Framework_2007_2012_DET.xlsx’

Use_SUT_Framework_2 100%[===================>]   1.40M  --.-KB/s    in 0.1s

2022-09-26 07:09:23 (9.58 MB/s) - ‘Use_SUT_Framework_2007_2012_DET.xlsx’ saved [1467803/1467803]

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [10]:
df = pd.read_excel("test_sheet.xlsx", sheet_name=None)

In [11]:
df.keys()

dict_keys(['ReadMe ', 'NAICS Codes', '2007', '2012'])

In [12]:
df_1 = pd.read_excel("test_sheet.xlsx", sheet_name='2007')
df_1.head()

,"The Use Table (Supply-Use Framework), 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 418,Unnamed: 419,Unnamed: 420,Unnamed: 421,Unnamed: 422,Unnamed: 423,Unnamed: 424,Unnamed: 425,Unnamed: 426,Unnamed: 427
0,[Millions of dollars],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Commodities/Industries,NaN,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including fe...",...,Federal national defense: Gross investment in ...,Federal Government nondefense: Consumption exp...,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intell...,Federal nondefense: Gross investment in struct...,State and local government consumption expendi...,State and local: Gross investment in equipment,State and local: Gross investment in intellect...,State and local: Gross investment in structures,Total use of products
4,Code,Commodity Description,1111A0,1111B0,111200,111300,111400,111900,112120,1121A0,...,F06S00,F07C00,F07E00,F07N00,F07S00,F10C00,F10E00,F10N00,F10S00,T019

In [13]:
!wget https://apps.bea.gov/industry/Release/XLS/GDPxInd/GrossOutput.xlsx

--2022-09-26 07:14:43--  https://apps.bea.gov/industry/Release/XLS/GDPxInd/GrossOutput.xlsx
Resolving apps.bea.gov (apps.bea.gov)... 192.149.12.17, 2610:20:3006:1::25
Connecting to apps.bea.gov (apps.bea.gov)|192.149.12.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 414953 (405K) [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet]
Saving to: ‘GrossOutput.xlsx’

GrossOutput.xlsx    100%[===================>] 405.23K  --.-KB/s    in 0.1s

2022-09-26 07:14:43 (3.57 MB/s) - ‘GrossOutput.xlsx’ saved [414953/414953]

In [14]:
df_n = pd.read_excel("GrossOutput.xlsx", sheet_name=None)

In [15]:
df_n.keys()

dict_keys(['Contents', 'TGO101-A', 'TGO101-Q', 'TGO103-A', 'TGO103-Q', 'TGO104-A', 'TGO104-Q', 'TGO105-A', 'TGO105-Q', 'TGO106-A', 'TGO106-Q', 'TGO107-A', 'TGO107-Q'])

In [ ]:
df_n = pd.read_excel("GrossOutput.xlsx", sheet_name='TGO101-A')
df_n

In [17]:
!wget http://www.historia.se/VolumeICh10Wages1860_.xls

--2022-09-26 07:19:54--  http://www.historia.se/VolumeICh10Wages1860_.xls
Resolving www.historia.se (www.historia.se)... 46.30.213.61, 2a02:2350:5:10a:80ef:e857:216c:ab34
Connecting to www.historia.se (www.historia.se)|46.30.213.61|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160768 (157K) [application/vnd.ms-excel]
Saving to: ‘VolumeICh10Wages1860_.xls’

VolumeICh10Wages186 100%[===================>] 157.00K   482KB/s    in 0.3s

2022-09-26 07:19:55 (482 KB/s) - ‘VolumeICh10Wages1860_.xls’ saved [160768/160768]

In [19]:
!wget https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_PO_monthly_hist.xls

--2022-09-26 07:28:05--  https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_PO_monthly_hist.xls
Resolving www.fhfa.gov (www.fhfa.gov)... 13.226.52.117, 13.226.52.73, 13.226.52.75, ...
Connecting to www.fhfa.gov (www.fhfa.gov)|13.226.52.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 132608 (130K) [application/vnd.ms-excel]
Saving to: ‘HPI_PO_monthly_hist.xls’

HPI_PO_monthly_hist 100%[===================>] 129.50K  --.-KB/s    in 0.04s

2022-09-26 07:28:05 (2.86 MB/s) - ‘HPI_PO_monthly_hist.xls’ saved [132608/132608]

In [23]:
!pip install xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)

In [25]:
!pip install --upgrade xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.8 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-2.0.1

In [4]:
%cd new_data
!pwd

/content/new_data
/content/new_data

In [5]:
df_n = pd.read_excel("HPI.xls", sheet_name=None)

In [8]:
df_n.keys()

dict_keys(['Downloadable--Series to91--FLAT'])

In [10]:
df_n = pd.read_excel("HPI.xls", sheet_name='Downloadable--Series to91--FLAT')

In [11]:
df_n

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Monthly FHFA House Price Index® for Census Div...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Month,East North Central\n(NSA),East North Central\n(SA),East South Central\n(NSA),East South Central\n(SA),Middle Atlantic\n(NSA),Middle Atlantic\n(SA),Mountain\n\n(NSA),Mountain\n\n(SA),New England\n\n(NSA),...,Pacific\n\n(NSA),Pacific\n\n(SA),South Atlantic\n(NSA),South Atlantic\n(SA),West North Central\n(NSA),West North Central\n(SA),West South Central\n(NSA),West South Central\n(SA),USA\n\n(NSA),USA\n\n(SA)
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1991-01-01 00:00:00,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,2022-02-01 00:00:00,301.47,302.92,352.68,352.1,324.94,326.3,566.11,567.39,355.92,...,451.79,451.85,402.91,401.44,357.27,358.96,386.73,386.66,380.55,380.74
378,2022-03-01 00:00:00,307.95,307.28,361.02,359.74,330.52,330.24,584.13,580.82,367.27,...,460.74,457.81,411.52,407.75,364.3,362.48,393.28,391.3,388.73,386.46
379,2022-04-01 00:00:00,314.51,311.02,364.67,361.75,336.9,333.97,596.7,589.71,376.4,...,469.1,463.94,420.69,416.03,374.07,369.72,404.74,400.69,397.17,392.63
380,2022-05-01 00:00:00,321,315.3,372.38,367.7,342.54,337.27,606.08,598.38,383.75,...,469.31,462.92,430.28,423.95,380.37,373.25,412.64,407.61,403.94,397.64
381,2022-06-01 00:00:00,321.33,314.15,378.02,372.68,346.51,341.68,599.47,593.14,381.54,...,464.63,459.99,431.73,426.35,378.45,370.73,416.08,408.69,404.44,397.96

In [13]:
df_n.iloc[2]

Unnamed: 0                         Month
Unnamed: 1     East North Central\n(NSA)
Unnamed: 2      East North Central\n(SA)
Unnamed: 3     East South Central\n(NSA)
Unnamed: 4      East South Central\n(SA)
Unnamed: 5        Middle Atlantic\n(NSA)
Unnamed: 6         Middle Atlantic\n(SA)
Unnamed: 7             Mountain\n\n(NSA)
Unnamed: 8              Mountain\n\n(SA)
Unnamed: 9          New England\n\n(NSA)
Unnamed: 10          New England\n\n(SA)
Unnamed: 11             Pacific\n\n(NSA)
Unnamed: 12              Pacific\n\n(SA)
Unnamed: 13        South Atlantic\n(NSA)
Unnamed: 14         South Atlantic\n(SA)
Unnamed: 15    West North Central\n(NSA)
Unnamed: 16     West North Central\n(SA)
Unnamed: 17    West South Central\n(NSA)
Unnamed: 18     West South Central\n(SA)
Unnamed: 19                 USA\n\n(NSA)
Unnamed: 20                  USA\n\n(SA)
Name: 2, dtype: object

In [14]:
columns = df_n.iloc[2]
df_new = df_n[4:]
df_new.columns = columns

In [15]:
df_new

2,Month,East North Central\n(NSA),East North Central\n(SA),East South Central\n(NSA),East South Central\n(SA),Middle Atlantic\n(NSA),Middle Atlantic\n(SA),Mountain\n\n(NSA),Mountain\n\n(SA),New England\n\n(NSA),...,Pacific\n\n(NSA),Pacific\n\n(SA),South Atlantic\n(NSA),South Atlantic\n(SA),West North Central\n(NSA),West North Central\n(SA),West South Central\n(NSA),West South Central\n(SA),USA\n\n(NSA),USA\n\n(SA)
4,1991-01-01 00:00:00,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
5,1991-02-01 00:00:00,100.91,100.97,101.02,100.62,100.15,100.37,98.43,98.8,101.73,...,100.13,100.53,100.61,100.5,100.48,100.52,99.85,99.62,100.4,100.47
6,1991-03-01 00:00:00,101.31,100.92,100.88,100.45,100.07,99.81,100.25,100.65,101.5,...,99.95,100.1,101.03,100.64,100.38,100.12,100.64,100.49,100.68,100.48
7,1991-04-01 00:00:00,101.7,101,100.81,100.44,99.59,99.28,100.32,100.41,100.98,...,100.15,100.11,100.93,100.47,100.79,100.36,100.37,100.05,100.69,100.34
8,1991-05-01 00:00:00,102.33,101.37,101.13,100.73,99.72,99.24,100.7,100.51,99.72,...,100.32,100.07,100.8,100.55,100.74,100.29,100.79,100.29,100.84,100.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,2022-02-01 00:00:00,301.47,302.92,352.68,352.1,324.94,326.3,566.11,567.39,355.92,...,451.79,451.85,402.91,401.44,357.27,358.96,386.73,386.66,380.55,380.74
378,2022-03-01 00:00:00,307.95,307.28,361.02,359.74,330.52,330.24,584.13,580.82,367.27,...,460.74,457.81,411.52,407.75,364.3,362.48,393.28,391.3,388.73,386.46
379,2022-04-01 00:00:00,314.51,311.02,364.67,361.75,336.9,333.97,596.7,589.71,376.4,...,469.1,463.94,420.69,416.03,374.07,369.72,404.74,400.69,397.17,392.63
380,2022-05-01 00:00:00,321,315.3,372.38,367.7,342.54,337.27,606.08,598.38,383.75,...,469.31,462.92,430.28,423.95,380.37,373.25,412.64,407.61,403.94,397.64
381,2022-06-01 00:00:00,321.33,314.15,378.02,372.68,346.51,341.68,599.47,593.14,381.54,...,464.63,459.99,431.73,426.35,378.45,370.73,416.08,408.69,404.44,397.96